services:
  backend:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - public
      - private
  frontend:
    build:
      context: front-end
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
      - /app/node_modules
    networks:
      - public
    depends_on:
      - backend

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m", "pytest", "--tb=short", "-p", "no:warnings"]
    volumes:
      - .:/app
    networks:
      - private
    depends_on:
      - backend

networks:
  public:
  private:
    driver: bridge
