name: CI Pipeline

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch
  pull_request:
    branches:
      - 'main'  # Triggers on pull request to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker Compose services
      run: |
        cd ../../software
        docker-compose up --build -d

    - name: Run Unit Tests
      run: |
        cd ../../software
        docker-compose run --rm tests pytest tests/unit-test

    - name: Run Integration Tests
      run: |
        cd ../../software
        docker-compose run --rm tests pytest tests/integration-test

    - name: Shut down Docker Compose services
      run: |
        cd ../../software
        docker-compose down
