name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker Compose services
      run: docker-compose up --build -d

    - name: Run Unit Tests
      run: docker-compose run --rm tests pytest tests/unit-test

    - name: Run Integration Tests
      run: docker-compose run --rm tests pytest tests/integration-test

    - name: Shut down Docker Compose services
      run: docker-compose down
